# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: pagenorma
email: davor.banovicl@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  pagnorma is a tool for literary translators for managing and organizing their translation projects. 
  You can keep track of your translation progress and organize your work efficiently by forecasting deadlines and monitor your monthly earnings. 
  View your translation side-by-side with the original text for easier comparison, with built in searchable glossary, concordance and AI commentary.

url: https://pagenorma.eu # the base hostname & protocol for your site, e.g. http://example.com

timezone: Europe/Zagreb

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

keep_files: [app]
include:
  - app
  - _pages

defaults:
  - scope:
      path: "app"
    values:
      layout: null